;//Alias header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2021/12/18 15:36:59

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

IDH_1000=MytoolUI.html	; MytoolUI
IDH_1001=病案工具.htm	; 1 病案工具
IDH_1004=感染病例报告卡.html	; 1.1 感染病例报告卡
IDH_1003=病案质量评分表.html	; 1.2 病案质量评分表
IDH_1002=流行病学调查表.html	; 1.3 流行病学调查表
IDH_1006=出院随访.htm	; 2 出院随访
IDH_1007=慢病报卡.htm	; 3 慢病报卡
IDH_1008=门诊日志.htm	; 4 门诊日志
IDH_1009=肿瘤报卡.htm	; 5 肿瘤报卡
IDH_1005=血气分析.htm	; 6 血气分析
