;//Map header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2021/12/18 15:36:59

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

#define IDH_1000	1000	; MytoolUI MytoolUI.html
#define IDH_1001	1001	; 1 病案工具 病案工具.htm
#define IDH_1004	1004	; 1.1 感染病例报告卡 感染病例报告卡.html
#define IDH_1003	1003	; 1.2 病案质量评分表 病案质量评分表.html
#define IDH_1002	1002	; 1.3 流行病学调查表 流行病学调查表.html
#define IDH_1006	1006	; 2 出院随访 出院随访.htm
#define IDH_1007	1007	; 3 慢病报卡 慢病报卡.htm
#define IDH_1008	1008	; 4 门诊日志 门诊日志.htm
#define IDH_1009	1009	; 5 肿瘤报卡 肿瘤报卡.htm
#define IDH_1005	1005	; 6 血气分析 血气分析.htm
